### ISSUE TITLE
When transpileOnly is enabled, ts-loader leaves in re-exports of types, causing webpack 4 to warn about export not being found

### ISSUE THREAD

**Issue by univerio** [TypeStrong/ts-loader#751] opened 2018-03-24 01:15 UTC
### Expected Behaviour

For a project like this:

```ts
// bar.ts
export {IFoo, FOO} from "./foo";
export type IBar = {};
```

```ts
// foo.ts
export type IFoo = {};
export const FOO = 1;
```

```ts
// index.ts
import {FOO, IFoo, IBar} from "./bar";

declare function foo(i: number): IFoo;
declare function bar(): IBar;
foo(FOO);
bar();
```

Regardless of whether `transpileOnly` is enabled, the output for bar.ts should be (assuming module=ESNEXT):

```js
export var FOO = 1;
```

### Actual Behaviour

The actual output is:

```js
export { IFoo } from "./foo";
export var FOO = 1;
```

which causes webpack to complain:

```
WARNING in ./src/bar.ts
1:0-34 "export 'IFoo' was not found in './foo'
 @ ./src/bar.ts
 @ ./src/index.ts
```

When `transpileOnly` is off, the module is correctly emitted. This may very well be a compiler bug, but I'm not sure how to use `tsc` to reproduce this.

### Steps to Reproduce the Problem

```
git clone https://github.com/univerio/ts-loader-type-export-issue
cd ts-loader-type-export-issue
yarn
./node_modules/webpack-cli/bin/webpack.js
```

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/univerio/ts-loader-type-export-issue

**Comment by johnnyreilly** [comment] 2018-03-24 07:41
> This may very well be a compiler bug, but I'm not sure how to use tsc to reproduce this.

I suspect this is a compiler issue yes. That said there may be good reason for it. I'd suggest asking a question on the Typescript project to confirm if this is expected behaviour or not. ts-loader is doing nothing special here; just hooking into the Typescript compiler API

**Comment by univerio** [comment] 2018-03-26 02:58
I think I understand it now. I think it has to do with the fact that `transpileOnly` uses `ts.transpileModule`, which is essentially equivalent to turning on `isolatedModules`. When compiling each module separately, the compiler does not have enough information to know whether an import is a type or not (see Microsoft/TypeScript#15231), so while it eliminates imports that are never used in a value position (which works for imported types that are not exported), it cannot know whether an export is a type or not. So, fundamentally, `ts.transpileModule` is incompatible with type re-exports.

This issue has cropped up now because webpack 4 warns about these invalid exports, but the final bundle otherwise works fine. Perhaps there's an option in webpack to silence these warnings?

**Comment by johnnyreilly** [comment] 2018-03-26 06:13
Thanks for investigating and reporting back - super helpful! It might be worth inquiring against the webpack repo for such an option and linking back to this. I'm not aware of an option myself but that doesn't mean it doesn't exist!

**Comment by univerio** [comment] 2018-03-26 21:31
Found the option:

```js
{
  stats: {
    warningsFilter: /export .* was not found in/,
  }
}
```

Perhaps we can add it to the readme?

**Comment by johnnyreilly** [comment] 2018-03-27 05:27
Sure - send a PR!

**Comment by FourwingsY** [comment] 2018-04-11 17:43
@univerio Oh yes i got it. I've set `config.module.strictExportPresence = true` on webpack config. Thanks a lot!

**Comment by enoshixi** [comment] 2018-06-25 15:57
This also works for me and gets the compiler to remove the type export all together:
``` typescript
import { IFoo } from "./foo";
export type IFoo = IFoo;
```

**Comment by bjeanes** [comment] 2019-03-06 04:21
That did not work for me, but the solution in https://github.com/babel/babel-loader/issues/603#issuecomment-418472968 did:

``` ts
import { T as a_T } from "./a";
export type T = a_T;
```

**Comment by bbil** [comment] 2019-10-17 00:20
I'm seeing this now in webpack `4.41.2`, and the warning looks different, causing the recommended regex to not suppress the warning.

```
Compiled with warnings.

./src/middleware/sagas/appStartHelper.ts
Attempted import error: 'StartConfig' is not exported from '@instore/middleware/sagas/appStartHelper'
```

Not sure if this is a result of the version of webpack, typescript, or maybe some munging from create-react-app.

**Comment by bbil** [comment] 2019-10-17 01:27
^^ To avoid a DenverCoder9 situation, here's an update.

The example `warningsFilter` is correct, but if you are working with an ejected `create-react-app` project, then you need to add this to the `build.js` script, not to the webpack configuration!

For whatever reason, the warning I posted above is not what you should be basing your regex on. Since the actual warning vs what was being displayed are different strings.

```
        messages = formatWebpackMessages(
          stats.toJson({
            all: false,
            warnings: true,
            errors: true,
            warningsFilter: [
              /export .* was not found in/
            ]
          })
        );
```

**Comment by Jessidhia** [comment] 2019-10-29 09:11
This is going to be an issue when using any compiler that has to work without having the full type information... like typescript itself in `--isolatedModules` mode. As long as there is no syntax to annotate type-only exports / reexports this is going to persist as a problem.

**Comment by johnnyreilly** [comment] 2019-10-31 07:59
I've reopened this issue following @MLoughry comments on the webpack 5 beta. It seems this issue may present with webpack 5 as well.

See https://github.com/webpack/webpack/issues/9802#issuecomment-547161433

If people could detail:

1. What they're experiencing
2. If there are any remedies

That would be helpful. It's not clear to me that the problems being experienced can be solved by ts-loader. Any "fix" would likely need to be implemented within the TypeScript APIs or handled by webpack configuration.

I'm reopening this ticket for visibility and in the hope that people can use this as a place to discuss the issues.

cc @andrewbranch @sokra

**Comment by stavalfi** [comment] 2019-10-31 08:52
I'm not using ts-loader and i see this problem anyways. (using babel-loader to compile typescript).

I solved it in super ugly way by doing:

> ```ts
> import { IFoo } from "./foo";
> export type IFoo = IFoo;
> ```

as @enoshixi mentioned.

**Comment by johnnyreilly** [comment] 2019-11-02 05:54
See https://github.com/microsoft/TypeScript/issues/34750 also as suggested by @andrewbranch

**Comment by Bnaya** [comment] 2019-11-02 12:39
it's possible to re-export types:
```ts
export type ExternalArgs = import("./internal/interfaces").ExternalArgsApi;
export type CreateObjectBufferOptions = import("./internal/api").CreateObjectBufferOptions;
```

**Comment by eltonchan** [comment] 2019-12-06 02:16
> ^^ To avoid a DenverCoder9 situation, here's an update.
> 
> The example `warningsFilter` is correct, but if you are working with an ejected `create-react-app` project, then you need to add this to the `build.js` script, not to the webpack configuration!
> 
> For whatever reason, the warning I posted above is not what you should be basing your regex on. Since the actual warning vs what was being displayed are different strings.
> 
> ```
>         messages = formatWebpackMessages(
>           stats.toJson({
>             all: false,
>             warnings: true,
>             errors: true,
>             warningsFilter: [
>               /export .* was not found in/
>             ]
>           })
>         );
> ```
Yes, I reported the same error, but it was not a warning, but an error, which puzzled me. I have set config.module.strictExportPresence = true， So the compilation still fails, no reason has been found so far

**Comment by eltonchan** [comment] 2019-12-09 10:24
> I think I understand it now. I think it has to do with the fact that `transpileOnly` uses `ts.transpileModule`, which is essentially equivalent to turning on `isolatedModules`. When compiling each module separately, the compiler does not have enough information to know whether an import is a type or not (see [microsoft/TypeScript#15231](https://github.com/microsoft/TypeScript/issues/15231)), so while it eliminates imports that are never used in a value position (which works for imported types that are not exported), it cannot know whether an export is a type or not. So, fundamentally, `ts.transpileModule` is incompatible with type re-exports.
> 
> This issue has cropped up now because webpack 4 warns about these invalid exports, but the final bundle otherwise works fine. Perhaps there's an option in webpack to silence these warnings?

But I reported the error directly, and the compilation failed.

**Comment by eltonchan** [comment] 2019-12-09 11:26
> config.module.strictExportPresence = true

should be set config.module.strictExportPresence = false

**Comment by johnnyreilly** [comment] 2020-01-04 16:10
With https://github.com/microsoft/TypeScript/pull/35200#issuecomment-570727237 merged I wonder if we should consider changing the default `tsconfig` compiler flag to:

`--importsNotUsedAsValue "preserve"`

For webpack 5 given that:

> preserve keeps imports used only for types in the emit as a side-effect import

I think this might resolve the issue reported here so most users just don't bump into it.

We'd look to do this as a breaking changes version if we did.

A little background: as policy we deliberately don't change the default compiler flags often. But this would seem to be a case which is very webpack specific and consequently appropriate. 

I'd be interested in your thoughts @andrewbranch ?

**Comment by andrewbranch** [comment] 2020-01-05 22:29
I don’t think you need to change the default. You can still do `export type { T } from './m'` to solve the original issue here regardless of the emit setting. We will probably recommend `preserve` or `error` for new projects going forward, but I don’t see a strong reason to override the default in ts-loader, unless I’m missing something.

**Comment by johnnyreilly** [comment] 2020-01-06 08:10
Yeah that seems reasonable. I may put some docs in ts-loader to explicitly recommend using one of those too. Happy New Decade by the way! 🥰🤗

**Closed** 2020-03-13 09:11 UTC
Labels: wontfix
