### ISSUE TITLE
Webpack --watch Issue

### ISSUE THREAD

**Issue by raybooysen** [TypeStrong/ts-loader#176] opened 2016-03-30 12:52 UTC
I'm seeing this odd issue when running with `webpack --watch`.

If I run the command above and there is an error in the TS, any syntax issue, ts-loader correctly tells me that there has been an error.

However, then it seems like I'm dead in the water.  If I change any code, webpack doesn't seem to re-run the cycle and I have to restart.  Is this known?

**Comment by B3nCr** [comment] 2016-04-06 15:48
I'm not sure if it's related but for me the --watch option only watches the first file in my app, rather than all the files.

**Comment by toolness** [comment] 2016-04-06 20:52
Hmm, I saw this issue when evaluating whether to use `ts-loader` and it seemed like a dealbreaker, so I followed the `README.md` instructions to set up a basic `tsconfig.json` and `webpack.config.js`, and I'm unable to reproduce your problem... I've tried:

* Introducing JS syntax errors (e.g. `foo()o;`)
* Introducing typescript errors (e.g. `function foo(i : number){} foo("HI");`)

and webpack correctly logs the error, and I fix them and webpack correctly rebuilds the project...

@raybooysen can you provide a simplified test case or anything?

**Comment by jbrantly** [comment] 2016-04-11 03:26
Out of curiosity, what version of webpack are you using?

**Comment by raybooysen** [comment] 2016-04-11 08:09
1.12.14 for me.

@toolness I'll try

**Comment by lionelB** [comment] 2016-10-17 12:00
Hello

I add the kind of issue. not sure it's related
I currently use webpack through webpack-stream (`^3.0.0`) and ts-loader (~0.8.0) from a gulp task
First symptom was the error crash the build, so I added a `.on('error', fn)` event listener and wich fix the crash problem, but leave the code un-updated if I fix the code after.

**Comment by johnnyreilly** [comment] 2016-10-22 07:42
Closing as there doesn't seem to be anything to do

**Closed by johnnyreilly** 2016-10-22 07:42 UTC
