### ISSUE TITLE
Status code of log message wrong

### ISSUE THREAD

**Issue by ThYpHo0n** [TypeStrong/ts-loader#311] opened 2016-10-12 13:15 UTC
Hey,

first of all: this is a minor thing and just annoying but the log output gives a wrong status code for the ls-load output:
`[ERROR] ts-loader: Using typescript@2.0.3 and /workspace/cool-project/src/main/resources/tsconfig.json`

It was already mentioned in other projects like https://github.com/eirslett/frontend-maven-plugin/issues/382

Would be really cool to see this fixed to have a clean output.

**Comment by johnnyreilly** [comment] 2016-10-12 13:31
Closing as duplicate of https://github.com/TypeStrong/ts-loader/issues/249

**Closed by johnnyreilly** 2016-10-12 13:31 UTC
