### ISSUE TITLE
How to generate all js file for every ts files to dynamic require

### ISSUE THREAD

**Issue by lichnow** [TypeStrong/ts-loader#1090] opened 2020-04-16 08:36 UTC
### Expected Behaviour
Compile all .ts file to .js file like `tsc` command,so I can scan `config` dir dynamic to include all config file
<img width="162" alt="QQ20200416-162913@2x" src="https://user-images.githubusercontent.com/1695900/79433552-d7ac4200-7fff-11ea-8766-b0ce170d8fb0.png">

### Actual Behaviour
Only generate .d.ts  and a `main.js` file...
<img width="145" alt="QQ20200416-163114@2x" src="https://user-images.githubusercontent.com/1695900/79433785-20fc9180-8000-11ea-8083-3b9dfa3aba52.png">

### Steps to Reproduce the Problem
Options
```
{
            configFile: path.resolve(config.paths.srcPath, 'tsconfig.json'),
            projectReferences: true,
            transpileOnly: false
        }
```

### Location of a Minimal Repository that Demonstrates the Issue.
none

**Comment by johnnyreilly** [comment] 2020-04-16 20:15
Closing as this is not a bug; it's intended behaviour

**Closed by johnnyreilly** 2020-04-16 20:15 UTC
