### ISSUE TITLE
Required Templates Not Updating On Change

### ISSUE THREAD

**Issue by daniel-nagy** [TypeStrong/ts-loader#562] opened 2017-06-23 19:51 UTC
When I make changes to an HTML file the changes are not added to the bundle. I've created a simple demo to show that adding the typescript loader is the culprit.

[webpack-test.zip](https://github.com/TypeStrong/ts-loader/files/1098892/webpack-test.zip)

Run `yarn` to fetch the dependencies then run `yarn run start` to start the dev server. Make some changes to `src/app.html` and save. You will notice that the changes are not added to the bundle. Now remove the `typeScriptRule` rule from the webpack config and restart the server. Now when you make changes to `src/app.html` you will see the HMR updates in the browser.

If you can help me get this working I would really appreciate it.

**Comment by arackaf** [comment] 2017-07-05 00:28
I'm seeing similar.  It seems .ts and .tsx files only sometimes (and rarely) trigger WDS to re-load (no HMR, just basic WDS auto-reload).

I've cleared my node_modules out and re-installed everything, but no improvement.  This started happening right after the upgrade to webpack 3.

If anyone wants to repro, my repo is here https://github.com/arackaf/booklist 

Basically cd into react-redux directory, and `npm i` then `npm start` to fire off WDS.  Editing most files in `react-redux/modules/books` will not trigger a WDS reload.

**Comment by johnnyreilly** [comment] 2017-07-05 13:15
Sounds like this is a webpack 3 issue rather than ts-loader?

**Comment by arackaf** [comment] 2017-07-05 15:23
I wish I could say.  The webpack folks haven't heard of this happening, so I figured it was probably something in the ts-loader not playing well with wp3

**Comment by johnnyreilly** [comment] 2017-07-05 15:26
If you're able to look into this I'd really appreciate it. I'm pretty snowed right now

**Comment by arackaf** [comment] 2017-07-05 15:32
This is a rare time in which I actually have a bit of time to spare - I'd be happy to help as able, but I'm afraid I wouldn't know what to look for.  Is there anything specific I should look at?  Any breakpoints deep within node_modules I need to set?

**Comment by johnnyreilly** [comment] 2017-07-05 18:51
Thanks! I'd start by confirming that webpack 2 works and webpack 3 doesn't. Once you've done that try to identify the working code path in webpack 2 (I find console.log is my friend in these circumstances - just hack tons of logging into ts-loader / webpack to identify what's happening. Then apply the same logging to webpack 3 and contrast to identify the cause of different behaviour. Hope that helps!

**Comment by arackaf** [comment] 2017-07-08 01:57
Bad news is, that's way deeper than I'd reasonably be able to tackle - I've never once peaked in the webpack code (not for lack of curiosity, just lack of time :))

Good news is, upgrading to webpack 3.1 appears to have fixed things.  It's not my case, so I can't close it, but this appears to be fixed.

**Comment by johnnyreilly** [comment] 2017-07-08 04:42
Thanks @arackaf! Closing

**Closed by johnnyreilly** 2017-07-08 04:42 UTC
