### ISSUE TITLE
ts-loader generating definition file in wrong directory

### ISSUE THREAD

**Issue by jombie** [TypeStrong/ts-loader#190] opened 2016-04-30 13:28 UTC
I am creating a new issue here as discussed in [typescript Issue] (https://github.com/Microsoft/TypeScript/issues/7958#issuecomment-215914134)
I am using typescript version 1.9.0-dev.20160412 and ts-loader version 0.8.2 as below
My tsconfig.json is as below:
```sh
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "moduleResolution": "node",
    "preserveConstEnums": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "noEmitOnError": false,
    "forceConsistentCasingInFileNames": true,
    "removeComments": false,
    "sourceMap": true,
    "jsx": "react",
    "outDir": "./lib",
    "declaration": true
  },
  "exclude": [
    "node_modules",
    "dist",
    "typings/browser",
    "typings/browser.d.ts"
  ]
}
```
My project folder structure is as below:
```sh
work/
`-- projects
    `-- projectx
        |-- dist
        |-- src
        `-- tsconfig.json
```
I am trying to compile and generate .d.ts files inside the 'lib' dir but this creates the .d.ts file inside folder with parent attached to lib i.e
```sh
work/
`-- projects
    `-- projectx
        |-- src
        |-- dist
        |   `-- work
        |       `-- projects
        |           `-- projectx
        |               `-- dist
        |                   `-- lib
        |                       `-- src
        |                           `-- index.d.ts
        `-- tsconfig.json
```

I was expecting it to be as :
```sh
work/
`-- projects
    `-- projectx
        |-- dist
        |   `-- lib
        |       `-- src
        |           `-- index.d.ts
        |-- src
        `-- tsconfig.json 
```
**dist** dir above is given in the webpack.config.js as  below:
```sh
output: {
    path: path.join(__dirname, '/dist'),
    filename: outputFile,
    library: libraryName,
    libraryTarget: 'umd',
    umdNamedDefine: true
  }
```
Sample project with the above mentioned error  [Sample Project](https://github.com/jombie/projectx).
It works as expected with the version 0.8.0 of ts-loader

**Comment by leftstick** [comment] 2016-05-02 08:55
Same issue

**Comment by chrisnicola** [comment] 2016-05-02 22:44
Actually even with 0.8.0 it outputs far more of the directory structure than I would expect. Instead of 

```
dist/
`--index.d.ts
`--index.js
`--directives
   `--directive.js
   `--directive.d.ts
```

I get:

```
dist/
`--index.d.ts
`--index.js
`--src/module/directives
   `--directive.js
   `--directive.d.ts
```

Strangely though, this problem only happens if I specify files other than `index.ts` in the `files` section of my `tsconfig.json`.

**Comment by chrisnicola** [comment] 2016-05-02 23:28
So I did some further testing. It turned out I can do this but I needed to create a `tsconfig.build.json` specifically for my build and pass it to the loader. Also `outDir` needs to be `./` or it will be appended to the output folder from webpack.

In 0.8.2 this is definitely broken though, it expands the full original root path for each `d.ts` file it outputs.

**Comment by donaldpipowitch** [comment] 2016-05-13 20:27
I have the same problem with `0.8.2`. `0.8.1` seems to work.

**Comment by Bartzy** [comment] 2016-06-05 16:09
Can confirm (since 0.8.2). This was reported on #186.

**Comment by jukibom** [comment] 2016-06-23 14:38
Yep, seeing this too. Stuck on 0.8.1 for now (really wish I could comment package.json but oh well)

**Comment by hartjus** [comment] 2016-07-22 17:51
I can confirm I'm seeing this issue on 0.8.2.  The d.ts files are being generated in a full absolute on the file system, rather than the relative path in the project.

Expected:
```
dist/
  app/
    Class.d.ts
```

Actual:
```
dist/
  users/
    shared/
      workspace/
        project/
          dist/
            app/
                Class.d.ts
```

**Comment by autochthe** [comment] 2016-08-15 21:47
#238 is a duplicate issue that includes a minimal example demonstrating this bug

**Comment by ulitiy** [comment] 2016-09-03 16:23
Any workarounds? Maybe somehow explicitly set the path?

**Comment by jombie** [comment] 2016-09-04 20:25
Workaround for now is give path as
"outDir": "../../../../lib"

Number of backslashes = directory depth from root (/) till your project

**Comment by autochthe** [comment] 2016-09-05 00:44
That sounds terrible, but maybe we are getting close to a solution. If you
move the project to a different directory you just have the bug again,
except this time it can leak *outside* the project.  However, if the depth
of the project was detected programmatically and the outDir corrected
automatically that would solve the issue.

**Comment by aliatsis** [comment] 2016-09-28 20:44
+1

**Comment by johnnyreilly** [comment] 2016-10-21 05:59
Fixed on 0.9.3

**Closed by johnnyreilly** 2016-10-21 05:59 UTC

**Comment by orefalo** [comment] 2018-04-13 01:26
Same issue in 4.2.0

**Comment by gluons** [comment] 2018-06-04 14:49
Same issue in 4.3.0

**Comment by johnnyreilly** [comment] 2018-06-04 14:54
Would someone like to supply a minimal repro repo and investigate this?

**Comment by gluons** [comment] 2018-06-04 17:39
@johnnyreilly OK. I've created it.

Here: https://github.com/gluons/ts-loader-declaration-issue

Should I raise new issue?

**Comment by johnnyreilly** [comment] 2018-06-04 18:00
Thanks - it's fine to use this issue! Now, let's see how dedicated you are...  Would you be up for doing some investigation?

To give you a heads up, here's the pr that fixed the issue last time: https://github.com/TypeStrong/ts-loader/pull/307/files

Looks like the important stuff was in the `ensureTypeScriptInstance` function in the `index.ts` file.

Of course that was a long time ago, the relevant code now seems to be in the `provideDeclarationFilesToWebpack` function of the `afterCompile.ts` file.

Possibly worth investigating what `compilation.compiler.context` is these days - I've an idea it may have changed with webpack 4 but I'm not certain. 

Also worth checking: when did this functionality stop working? Which version of ts-loader first presents the problem?

**Comment by gluons** [comment] 2018-06-05 17:30
I don't know which version that this problem begin.

How can I help you? Maybe I will help you when I'm free.

**Comment by asual** [comment] 2018-06-06 12:15
Adding something like ```context: path.resolve("src")``` to the Webpack config is fixing this issue for me. Thanks @johnnyreilly!

**Comment by johnnyreilly** [comment] 2018-06-06 17:04
Thanks for sharing the workaround @gluons!

@jamesots 

> I'm not sure how to fix it though, without potentially breaking other things.

My advice: get something that seems to work for you. Ignore failing tests and submit a PR. I'll take a look and advise. If it's promising I'll try and help you get it over the finish line

**Comment by r-hannuschka** [comment] 2018-07-07 16:44
Got the same issue with ts-loader 4.4.1. 

my tsconfig.json for webpack looks like this.

```
{
    "extends": "./tsconfig",
    "compilerOptions": {
        "rootDir": "./src",
        "outDir": "./dist/umd"
    }
}
```

webpack.config.js
````
    output: {
        ...
        path: config.getOutDirectory(),
    },
    ...
     {
            test: /.*\.tsx?$/,
            use: [{
                loader: "ts-loader",
                options: {
                    configFile: config.getTsConfigFile(),
                },
            }],
        ...
```
This will create following folder structure: 

dist 
  |-- dist 
  |      |- umd 
  |            |- all typings
  |-- umd
         |- bundle.js 

What worked for me now was to add compilerOptions to ts-loader options and set the outDir to the basename of my output directory ( ./dist/umd -> umd )

{
 ...
 {
            test: /.*\.tsx?$/,
            use: [{
                loader: "ts-loader",
                options: {
                    compilerOptions: {
                        outDir: basename(config.getOutDirectory()),
                    },
                    configFile: config.getTsConfigFile(),
                },
            }],
   ...
}

**Comment by JonWallsten** [comment] 2018-08-16 13:18
I have the same problem. The path's base when generating declaration seems to be the outDir. But for the typescript compiler it's the project root. I can take a look at this and submit a PR if I find a solution.

**Comment by gluons** [comment] 2018-08-27 06:14
@johnnyreilly I've investigated `provideDeclarationFilesToWebpack` with [my repo](https://github.com/gluons/ts-loader-declaration-issue).  
Thank you for your hint.

`compilation.compiler.context` is my current working directory.  
`declarationFile.name` will give the absolute path to declaration file within the same place as source file.

So, after `path.relative`, the final path will contain `src`

![default](https://user-images.githubusercontent.com/4688092/44642752-d9269200-a9f7-11e8-8987-f361f3488725.png)

---

If I set `outDir` in my `tsconfig.json` to `dist`, `declarationFile.name` will contain `dist` instead.  
(This may be correct 😅)

![default](https://user-images.githubusercontent.com/4688092/44643017-163f5400-a9f9-11e8-9f26-ea4a72fab370.png)

---

Maybe I should `path.relative` the `declarationFile.name` with [webpack's `output.path`](https://webpack.js.org/configuration/output/#output-path).  
But I don't know what to do. 😅

**Comment by johnnyreilly** [comment] 2018-08-27 06:33
Hey @gluons,

Thanks for the detail. The issue should be resolved by this PR: https://github.com/TypeStrong/ts-loader/pull/822

I'm planning to merge and release this in future. Feel free to test out the PR ahead of release. Early feedback is always welcome!

**Comment by tedchirvasiu** [comment] 2018-11-04 20:55
Hello, for me the issue seems to be back since 5.0.0. Versions 4.3.0 and 4.5.0 were fine.

I made a minimal repo to reproduce the problem:
https://github.com/tedchirvasiu/ts-loader-declaration-output-dir-issue

Running "npm run build" will correctly place the .d.ts files in the dist folder since I'm using 4.5.0 there. However, if I upgrade to 5.0.0 (or @latest which is 5.3.0 as of right now) it puts the d.ts files at the root of the project.
Webpack's output path is set to "path.resolve(__dirname, 'dist')" and tsconfig's "outDir" is set to "./".

**Comment by johnnyreilly** [comment] 2018-11-05 06:30
Hey @tedchirvasiu 

I'm pretty sure the changed behaviour is intentional - see the details here:

https://github.com/TypeStrong/ts-loader/pull/822

**Comment by tedchirvasiu** [comment] 2018-11-05 07:58
@johnnyreilly @gluons Sorry, my bad, you are right. Added the outDir to the compilerOptions and it works as expected.

```javascript
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: "ts-loader",
                options: {
                    compilerOptions: {
                        outDir: './dist'
                    }
                }
            }
        ]
    }
```

Thank you!
