### ISSUE TITLE
build bug with new version

### ISSUE THREAD

**Issue by Frozenfire92** [TypeStrong/ts-loader#931] opened 2019-05-07 20:11 UTC
### Expected Behaviour
it builds properly

### Actual Behaviour
it fails with this warning

```
./cypress/integration/bugtest/example.spec.ts
Module build failed (from ./node_modules/ts-loader/index.js):
/some_path/node_modules/ts-loader/node_modules/micromatch/index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
                                                   ^^^

SyntaxError: Unexpected token ...
```

### Steps to Reproduce the Problem
- a new cypress project, try adding typescript like in their [example](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/preprocessors__typescript-webpack)
- `npm run cypress:open`

If your ts-loader version is > 5.4.5 it will break. I confirmed switching to 5.4.5 it does not break

It appears to be caused by: https://github.com/TypeStrong/ts-loader/pull/928/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R57

and I see similar issues on other projects that may be realted: https://github.com/micromatch/micromatch/issues/159 or https://github.com/BrowserSync/browser-sync/issues/1682

**Comment by B3zo0** [comment] 2019-05-07 20:44
see https://github.com/TypeStrong/ts-loader/issues/929

**Comment by andrewbranch** [comment] 2019-05-19 02:11
Closing as duplicate of #929. Thanks @B3zo0 👍

**Closed by andrewbranch** 2019-05-19 02:11 UTC
Labels: duplicate
