### ISSUE TITLE
Mixed relative and absolute paths in errors

### ISSUE THREAD

**Issue by altano** [TypeStrong/ts-loader#116] opened 2015-12-05 23:21 UTC
I'm trying to integrate VS Code with ts-loader and webpack so that I can get my errors in VS Code, but I'm encountering an issue where sometimes the errors have relative paths to the files and sometimes the paths are absolute.  It is making it difficult to do the integration.

To get absolute paths:
1. introduce a build error
2. run `webpack`
3. ts-loader will emit the errors with _absolute_ paths

To get relative paths:
1. have no build errors
2. run `webpack -w`
3. create an error in some file and save
4. ts-loader will emit the errors with _relative_ paths

**Comment by altano** [comment] 2015-12-05 23:46
I should note that it looks like webpack usually (always?) emits absolute file paths in errors so it might be nice to just match that.

Thanks!

**Comment by jbrantly** [comment] 2015-12-24 03:41
Apologies for the delay in getting back to you. I just did some tests using the latest version of webpack and ts-loader and I'm not seeing the same behavior you are.

First re: what webpack does. If I take ts-loader completely out of the mix and just run webpack against a simple JS file, I get an error like this:

> ERROR in ./app.js
Module not found: Error: Cannot resolve module 'a' in /home/jbrantly/ts-loader/test/basic
 @ ./app.js 1:8-20

Note that it is using relative paths. If I then add ts-loader back into the mix, I get something like this:

> ERROR in ./app.ts
(2,25): error TS2304: Cannot find name 'submodule2'.

The above was done without using watch mode, so similar to your first scenario where you said it reported absolute paths.

I'm believe though that in general webpack emits relative paths. Maybe there is something specific to your setup that is causing ts-loader to incorrectly report absolute paths? There are some specific cases where ts-loader will use absolute paths but they're almost always related to errors in the tsconfig.json file.

**Comment by jbrantly** [comment] 2016-02-10 04:51
Closing this but feel free to reopen if you're experiencing an issue.

**Comment by pmunin** [comment] 2017-08-13 09:09
Please reopen the issue, as it's still exists. I figured out how to reproduce it:

ts-loader triggers compilation of all files specified in ts.config (e.g. include "./src/**/*.ts"). However in webpack.config.js, there are specific entries specified (e.g. ./src/index.ts).
So for those .ts files that imported (directly or indirectly) by the entry of webpack.config.js - ts-loader generates correct relative file path (e.g. "ERROR in ./src/fileImportedByIndex.ts"). However if the message was in the file that's not imported (directly or indirectly) by entry, ts-loader generates absolute path.

Please fix this behavior.

**Comment by johnnyreilly** [comment] 2017-08-13 15:10
Could you provide a minimal repro please? That will make it easier to fix. If you'd like to have a go yourself I'm happy to provide guidance

**Comment by pmunin** [comment] 2017-08-13 17:33
Here you go:
[webpack-mixedpaths-issue.zip](https://github.com/TypeStrong/ts-loader/files/1220621/webpack-mixedpaths-issue.zip)

Copy of "Readme.md":

# What is this repo

This is repo demonstrating issue of mixed paths in webpack+ts-loader solution (https://github.com/TypeStrong/ts-loader/issues/116).

Looks like, the problem is that typescript compiles set of files (by default **.ts) different from webpack's set of files (dependency graph started from the entry specified in webpack.config.ts).

So for those modules that are not re-exported by the webpack's entry module - tsloader shows errors with absolute paths.
For those modules that are re-exported by the entry module error messages rendered with relative paths

## Steps to reproduce

Execute the following in command line:

```
npm install

npm run-script test
```

### Actual results

```
ERROR in c:\temp\webpack-mixedpaths-issue\notImportedNotExportedByEntry.ts
(8,1): error TS2304: Cannot find name 'not_imported_neither_exported'.

ERROR in c:\temp\webpack-mixedpaths-issue\importedButNotExportedByEntry.ts
(3,1): error TS2304: Cannot find name 'imported_but_not_exported_error'.

ERROR in ./importedAndExportedByEntry.ts
(2,1): error TS2304: Cannot find name 'imported_and_exported_error'.
```

### Expected results

```
ERROR in ./notImportedNotExportedByEntry.ts
(8,1): error TS2304: Cannot find name 'not_imported_neither_exported'.

ERROR in ./importedButNotExportedByEntry.ts
(3,1): error TS2304: Cannot find name 'imported_but_not_exported_error'.

ERROR in ./importedAndExportedByEntry.ts
(2,1): error TS2304: Cannot find name 'imported_and_exported_error'.
```

**Comment by johnnyreilly** [comment] 2017-08-13 18:09
Thanks!

**Closed** 2019-03-27 13:02 UTC
Labels: wontfix
