### ISSUE TITLE
Build fails if importing a component from node_modules library

### ISSUE THREAD

**Issue by ahelmel** [TypeStrong/ts-loader#278] opened 2016-09-07 09:26 UTC
I added a custom library from node_modules (something like: node_modules/@my-lib) imported a typescript component from this library in my code with:
`import { MyComponent } from '@my-lib/component/my-component';`

The typescript loader fails with the following message:
`Module build failed: Error: Typescript emitted no output for /Users/.../my-app/node_modules/@my-lib/component/my-component.ts at Object.loader (/Users/.../my-app/node_modules/ts-loader/index.js:456:15)`.

ts-loader version: 0.8.2
webpack version: 1.13.1
tsc version: 1.8.10

**Comment by Tiedye** [comment] 2016-09-08 00:40
I am having a similar issue, however, it only manifested when I removed a couple entries from my webpack configuration.  I have no clue why.  The module didn't even output to either of the entries I removed.

I'm using the new typescript/webpack though:
ts-loader: 0.8.2
webpack: 2.1.0-beta.21
tsc: 2.0.2

**Comment by g3r4n** [comment] 2016-09-27 09:15
Got the same issue. any solution ?

**Comment by g3r4n** [comment] 2016-09-27 09:56
I find a solution : i passed from Typescript@2.0.3 to Typescript@21.8.10

**Comment by sumeet70** [comment] 2016-10-03 05:12
Enguerrand,
Can you please explain how did you fix the error. I am not able to follow your comment related to type script versions.

**Comment by g3r4n** [comment] 2016-10-03 07:23
Execute the foowing command line : 
`
npm install typescript@1.8.10 -g
npm install typescript@1.8.10 -D
npm install typescript@1.8.10
`
It will install typescript v1.8.10 as global package, dev dependencies package and local package.

**Comment by skysteve** [comment] 2016-10-10 15:15
Also getting this with TS 2.0.3, and downgrading TS is not an option because of some of the things we're using.

Weirdly if I npm link the module in question it works fine, but again that's not really an ideal solution

**Comment by johnnyreilly** [comment] 2016-10-10 15:42
If someone is able to produce a repo which demonstrates the problem that could be helpful.   From what people have said this repo should **work** with TS 1.8 but **not work** with TS 2.0.  If that exists then it's a starting point for someone to investigate this.

**Comment by skysteve** [comment] 2016-10-11 11:17
@johnnyreilly https://github.com/skysteve/ts-bug-example-2 is about the simplest example I could get. Let me know if you need any more details, but certainly on my mac on node v 6.6 I can replicate the issue.

**Comment by johnnyreilly** [comment] 2016-10-16 20:53
Could you retest with ts-loader v0.9.3? We've just added `allowJs` support which may remedy the issue.

**Comment by stevejhiggs** [comment] 2016-10-18 07:36
Problem persists with 0.9.3

**Comment by basarat** [comment] 2016-11-09 05:47
`typestyle` seems incompatible with ts-loader. 

```
ERROR in ./~/typestyle/csx/index.ts
Module build failed: Error: Typescript emitted no output for /Users/syedb/REPOS/tmp/browsertypestyle/node_modules/typestyle/csx/index.ts
    at Object.loader (/Users/syedb/REPOS/tmp/browsertypestyle/node_modules/ts-loader/dist/index.js:27:15)
```
Sample project: 
[browsertypestyle.zip](https://github.com/TypeStrong/ts-loader/files/580017/browsertypestyle.zip)

Use `npm install` and `npm start`. There we get the error. 

Note : awesome-typescript-loader works with it, but it has its own issues that I'd rather not get into here. Mentioning it as its something that could to debugged to figure out root cause / fix :rose:

**Comment by johnnyreilly** [comment] 2016-11-09 06:18
Thanks for the repro @basarat - I'd actually rather forgotten about this issue. I'll try and take a look when I get a moment. Hope your having fun in the USA - what a time you picked for a holiday!

**Comment by basarat** [comment] 2016-11-09 06:55
Created a PR with a simpler repro : https://github.com/TypeStrong/ts-loader/pull/365 and note about what needs fixing :rose:

**Comment by basarat** [comment] 2016-11-13 21:58
Advice to any library authors shipping `.ts` files as the *main* way for ts consumption: I did the same for typestyle as an experiment and the results were not satisfactory and will never go there again. Reasons covered here : https://github.com/typestyle/typestyle/releases/tag/v0.7.0 Suggest you use `outDir` + `.js` + `.d.ts` as well :rose: ❤️

**Comment by johnnyreilly** [comment] 2016-11-14 06:24
Sounds painful!

**Comment by basarat** [comment] 2016-11-14 06:41
@johnnyreilly the lesson was painful. But the setup isn't:

* tsconfig
* code in `src/`
* outDir in `lib/`
* Done :rose:

**Comment by johnnyreilly** [comment] 2016-11-14 06:58
:tulip: So does the change you were talking about making to ts-loader still stand?

**Comment by basarat** [comment] 2016-11-14 07:30
I have the lost the will to implement it and would not recommend anyone to write a package that ships `.ts` + `.js` and instead people should use `outDir` + `.d.ts` + `.js`. 

Again for those interested reasons, the following bad things happen if you ship `.ts` + `.js` files : 

* If your package is used in nodejs by someone using `outDir`, your package messes up other peoples `outDir` option.
* As new stricter TypeScript compiler options are implemented they cannot be used by people that use your package unless you update your package to compile with those options as well.


# Help wanted :rose:

We can provide an *additional* error message if path contains `node_modules` that says: 

> Since the file is in `node_modules` you should not need to recompile .ts files in `node_modules` and should contact the package author to request them to use `--declaration --outDir`. More https://github.com/TypeStrong/ts-loader/issues/278

**Comment by johnnyreilly** [comment] 2016-11-14 07:49
Thanks for the investigation and write up @basarat. What you've said completely makes sense. I like the idea of the error message you suggest. Would it be straightforward to implement?

**Comment by basarat** [comment] 2016-11-14 08:01
> Would it be straightforward to implement?

From https://github.com/TypeStrong/ts-loader/blob/a438869c2a6ac97d176af4e5aac268838d4a3350/src/index.ts#L34-L36

```ts 
    if (outputText === null || outputText === undefined) {
        throw new Error(`Typescript emitted no output for ${filePath}`);
    }
```
To :
 
```ts
    if (outputText === null || outputText === undefined) {
        const additionalGuidance = filePath.indexOf('node_modules') !== -1 
        ? "You should not need to recompile .ts files in node_modules and should contact the package author to request them to use --declaration --outDir. More https://github.com/TypeStrong/ts-loader/issues/278"
        : "";
        throw new Error(`Typescript emitted no output for ${filePath}.${additionalGuidance}`);
    }

```

Ofcourse this is untested code and devil will be in the details + adding a test similar to https://github.com/TypeStrong/ts-loader/pull/365 :rose:

**Comment by johnnyreilly** [comment] 2016-11-14 08:15
Nice!

**Comment by johnnyreilly** [comment] 2016-11-14 08:28
FWIW it might be worth turning your findings into a blog post (if you're so minded). It's always an idea to spread the word when it comes to good practice and it seems like this is still new territory. Have you any idea if the TypeScript team have published any thoughts on this? 

Can't stop thinking of this: http://e.lvme.me/u33yl35.jpg

**Comment by HerringtonDarkholme** [comment] 2016-11-19 03:55
Sorry I still didn't get the point in the issue by just reading  :disappointed:

The problem is "if library author ship .ts in npm package, ts-loader cannot compile it in node_modules". Is this right?

**Comment by johnnyreilly** [comment] 2016-12-05 21:22
@HerringtonDarkholme yes that's about right.  There's now a warning when this happens

**Comment by peeter-tomberg** [comment] 2016-12-06 11:19
As a sidenote, I ran into this problem on a Mac. Everything works fine on a windows machine but all hell breaks loose on a Mac machine.

**Comment by HerringtonDarkholme** [comment] 2016-12-06 11:28
I'm not sure if it is relevant. But https://github.com/laco0416/light-ts-loader 's approach is quite interesting. It skips all type checking at build time. (Checking is done in editor or separate tsc call).

Maybe you can try the `transpileOnly` flag in ts-loader.

**Comment by ricklove** [comment] 2016-12-31 19:30
@basarat Thank you!

I've been pulling my hair out trying to get this to work. I thought pure .ts would be great, but it's not supported by the Typescript team (which makes sense because how would anybody use your library).

But all, I had to do was what you said and everything works:

- In tsconfig.ts:
    - Set outDir : 'lib'
    - Set definition : true
- In import statements:
    - Add /lib to the end: 
        - @told/platform
        - @told/platform/lib

Thanks!

**Comment by basarat** [comment] 2016-12-31 20:51
@ricklove thanks ❤ 

Minor : you don't need to use lib in import if you just want to use the main entry point.  For that you should add typingsto your pakckage.json. Eg https://github.com/typestyle/typestyle/blob/master/package.json#L6 🌹

**Comment by kpudlik** [comment] 2017-01-05 00:19
Unfortunately shipping js/d.ts files is not a solution for me. I have 2 private repositories:
- `project-web`
- `project-common`

Both repos are written in Typescript.
`project-web` depends on `project-common` so I decided to fetch `project-common` github repository by using npm and just do something like this in `project-web`:

`import { CommonComponents } from 'project-common'`

The problem is that I can't provide precompiled js/d.ts (mainly because inlining sass files in ts files which is handled by webpack like: `{ styles: [require('sample.sass')] }` so I need to bundle/compile two pure TS repos together to one bundle file (one comes from node_modules). Of course error occurs. The funny thing is that it occurs randomly.. Any solutions?
```
ERROR in ../~/project-common/index.ts
Module build failed: Error: Typescript emitted no output for /Users/kpudlik/project-web/node_modules/project-common/index.ts
    at Object.loader (/Users/kpudlik/erento/project-web/node_modules/ts-loader/index.js:458:15)
 @ ./app/app.module.ts 3:26-54
```

**Comment by ricklove** [comment] 2017-01-17 22:16
@basarat

What I have done so I don't need to include "/lib" in the import statements is to make an index.js file that exports the lib as the main entry point:

index.ts:

    export * from './lib'

That works fine for me unless I need a specific file, but it's not a terrible inconvenience as is.

I haven't used typings for my own projects, but if I run into problems, I'll research that.

**Comment by basarat** [comment] 2017-01-18 07:25
@ricklove like this : https://github.com/typestyle/typestyle/blob/82e793d49700443781e59606bb16d91cd912d51c/package.json#L5 :rose:

**Comment by kanitw** [comment] 2017-02-17 01:21
@basarat 

> If your package is used in nodejs by someone using outDir, your package messes up other peoples outDir option.

For an NPM package, if we ship js files in `outDir` and ship ts files in `src`, would this still mess up other people's outDir option?  (I hope not.)

**Comment by basarat** [comment] 2017-02-17 02:22
> For an NPM package, if we ship js files in tsconfig.json's outDir (e.g., dist/ or build/) and ship ts files in src, would this still mess up other people's outDir option? (I hope not.)

No. Be sure to add `typings` path to your `package.json` :rose:

**Comment by madroneropaulo** [comment] 2017-03-14 14:52
So the solution is to force including both, d.ts and a js file on your module even if the packages are planned to be consumed only on a typescript project? that doesn't sound nice.

**Comment by AndyBarron** [comment] 2017-05-18 22:21
I often use this kind of structure to arrange my source code:
```
proj/
  package.json
  node_modules/ <- external deps
  src/
    node_modules/ <- my code
      client/
      server/
      shared/
```
This lets me use e.g. `import * as api from 'shared/api'` instead of having to use relative paths. Unfortunately, this triggers a false positive for this error message, because `ts-loader` sees `node_modules` in the path name and assumes I'm compiling `.ts` files from my deps. :/

Any way to fix this, either via project config or an upstream patch? It's killing me, Smalls!

**Comment by johnnyreilly** [comment] 2017-05-19 04:50
Hi @AndyBarron,

I guess you're being bitten by this: https://github.com/TypeStrong/ts-loader/blob/master/src/index.ts#L38

If you compile your own version of ts-loader without the check does it all work fine for you?  

I should say that whilst I understand the desire to avoid relative path hell (boy does it eat into my time trying to work our the right paths) I'd be rather hesitant to use your approach.

**Comment by AndyBarron** [comment] 2017-05-19 06:26
I'll give that a shot and get back to you.

If there's a better solution, I've yet to hear it 😛

**Comment by johnnyreilly** [comment] 2017-05-19 06:40
Yeah - I feel your pain

**Comment by johnnyreilly** [comment] 2018-04-13 11:53
I get so many issues on this I'm wondering about enabling this behaviour behind an opt-in flag

**Comment by clement911** [comment] 2018-04-17 09:13
I'm in the same boat here. We have a shared module that is imported by our main module and we would like to import the ts files from the shared module.

**Comment by johnnyreilly** [comment] 2018-04-17 11:00
OK - if someone wants to put together a PR which enables this I'll happily take a look. Don't worry about fixing the tests; I can help with that.

**Comment by amritk** [comment] 2018-12-20 02:34
I'm having this issue as well on Typescript 3.2.2 and ts-loader 5.3.1. Its strange though, it happens in one of my projects and doesn't work in another.

**Comment by mreiche** [comment] 2019-02-14 07:42
I'm facing this issue as well, but infrequently. Sometimes it works, sometimes not.
```
yarn start build
...
Done in 12.65s.
```
When try to build again:
```
yarn start build
...
ERROR in ./node_modules/t-systems-aurelia-components/src/value-converters/date-format-value-converter.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for xxx\node_modules\t-systems-aurelia-components\src\value-converters\date-format-value-converter.ts.
    at makeSourceMapAndFinish xxx\node_modules\ts-loader\dist\index.js:78:15)
    at successLoader (xxx\node_modules\ts-loader\dist\index.js:68:9)
    at Object.loader (xxx\node_modules\ts-loader\dist\index.js:22:12)
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper
...
error Command failed with exit code 2.
```

In `webpack.config.js`
```
{test: /\.ts$/, loader: "ts-loader", options: { allowTsInNodeModules: true }},
```

Edit: I fixed that by changing the aurelia global resources from:
```
.globalResources([
    PLATFORM.moduleName('t-systems-aurelia-components/src/value-converters/date-format-value-converter'),
    ...
]);
```
to
```
.globalResources([
    't-systems-aurelia-components/src/value-converters/date-format-value-converter',
    ...
]);
```
And it seems to work now everytime.

**Comment by kmannislands** [comment] 2019-03-25 20:37
I believe I am running into this after restructuring a project with lerna + yarn workspaces.
First I get this error:
```
ERROR in ~/directory/node_modules/@monorepo/shared/src/security.ts
Module build failed (from ~/directory/node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for ~/directory/node_modules/@monorepo/shared/src/security.ts. By default, ts-loader will not compile .ts files in node_modules.
You should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.
See: https://github.com/Microsoft/TypeScript/issues/12358
    at makeSourceMapAndFinish (~/directory/node_modules/ts-loader/dist/index.js:78:15)
    at successLoader (~/directory/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (~/directory/node_modules/ts-loader/dist/index.js:22:12)
 @ ~/directory/node_modules/@monorepo/shared/src/index.ts 76:9-30
 @ ./src/app/index.js
 @ multi ./src/app/index.js
```

and then when I add the specified flag, something like:
```js
{
  // rest of config...
  module: {
    rules: [
      {
        test: /\.[jt]sx?$/,
        loader: 'ts-loader',
        options: {
          allowTsInNodeModules: true,
        },
        exclude: /node_modules((?!@monorepo).)*$/,
        include: /node_modules\/@monorepo\/|src\//,
      },
    ]
  }
}
```

**Comment by ritmos** [comment] 2019-03-28 19:59
Hello dear typescripters. The issue is not because of ts-loader, but because **tsc defaults to exclude node_modules folder** (https://www.typescriptlang.org/docs/handbook/tsconfig-json.html). They have a bad example showing how to exclude files with "node_modules" in it which leads to confusion. I have oppened an issue for that.

In any case, in order to allow ts-loader consume typescript source files directly from node_modules: edit tsconfig.json and add all the needed packages there. Like for example:

_tsconfig.json_
```
{
"compilerOptions": { },
"include": [
   "node_modules/@company", // all modules bellow from the company will be available
   "node_modules/@company/module", // specific module from the company
    "node_modules/module" // specific module
  ]
}
```

Another option that also worked in my case is to set ts-loader option transpileOnly to true

**Comment by kmannislands** [comment] 2019-03-28 20:36
@ritmos yes, something similar ended up being the issue for me, not a bug with ts-loader after all

**Comment by andrewbranch** [comment] 2019-05-18 20:01
It looks like #773 fixed this—can this be closed, or are there any further concerns?

**Comment by johnnyreilly** [comment] 2019-05-18 21:11
I think you're right - closed.

**Closed** 2019-05-18 21:10 UTC
Labels: help wanted
