### ISSUE TITLE
Typescript syntax errors in happyPackMode with forked checker

### ISSUE THREAD

**Issue by voodoorider** [TypeStrong/ts-loader#602] opened 2017-08-11 17:42 UTC
I have cloned the examples directory  from this repo and inside the happyPack example added the following line:

`const array = [{} {}];` (missing comma)

to the bottom of the `fileWithoutError.ts` file and corrected the error in `fileWithError.ts` file 

and then ran `webpack`. 

No errors were reported. When I try to use incorrect type errors indeed are reported, but I am not sure this is enough...

**Comment by johnnyreilly** [comment] 2017-08-11 17:56
Hi @voodoorider - could you report this against fork-ts-checker-webpack-plugin's repo please? If using that plugin then error checking is done outside of ts-loader. The repo is here: https://github.com/Realytics/fork-ts-checker-webpack-plugin

**Comment by johnnyreilly** [comment] 2017-08-12 05:17
> No errors were reported. When I try to use incorrect type errors indeed are reported

Also could you clarify what you mean by this? I don't think I follow...

**Comment by voodoorider** [comment] 2017-08-12 06:29
HI @johnnyreilly. thanks for the reply. Sorry if I have made my self clear. I forked the repo to show you what I have in mind. Here's the commit https://github.com/voodoorider/ts-loader/commit/33fe0d30de15794e9f0bbabc061f7bf06760b4bc

**Comment by johnnyreilly** [comment] 2017-08-12 08:02
Thanks - @pietr-oles any thoughts?

**Comment by johnnyreilly** [comment] 2017-08-12 08:03
Sorry @piotr-oles I meant

**Comment by piotr-oles** [comment] 2017-08-16 11:17
`fork-ts-checker` reports only semantic errors, syntax errors should be checked by ts-loader and as far as I know it's how it works in `transpileOnly` mode. Maybe it's because of happy-pack mode? I think it should not be hard to add flag to `fork-ts-checker` plugin to check syntax errors.

**Comment by johnnyreilly** [comment] 2017-08-16 14:48
I didn't realize that distinction was in place. When I get a moment I'll see if flipping the happypack mode switch makes a difference and report back. I was under the impression transpileOnly didn't report syntax errors - let's find out!

**Comment by johnnyreilly** [comment] 2017-08-17 05:39
I've done a test and this issue only presents when using `happypackMode`....

**Comment by johnnyreilly** [comment] 2017-08-17 05:46
I think the issue is here: https://github.com/TypeStrong/ts-loader/blob/master/src/index.ts#L214

```ts
    // _module.errors is not available inside happypack - see https://github.com/TypeStrong/ts-loader/issues/336
    if (!instance.loaderOptions.happyPackMode) {
        registerWebpackErrors(
            loader._module.errors,
            formatErrors(diagnostics, instance.loaderOptions, instance.compiler, { module: loader._module })
        );
    }
```

In `happyPackMode` we cannot register transpile errors with webpack and so this info is lost. BTW the same issue would presumably apply if using thread-loader instead of happypack.  Same principle; ts-loader cannot register errors with webpack.

There's nothing that we can do from a ts-loader perspective here.  

>  I think it should not be hard to add flag to fork-ts-checker plugin to check syntax errors.

If you could look at this that would be awesome!

**Comment by voodoorider** [comment] 2017-08-17 06:35
> BTW the same issue would presumably apply if using thread-loader instead of happypack.

Confirmed. TBH we are using `thread-loader` in our project but I had some issues running `thread-loader` example so I used `happy-pack`. Anyway as you said, it is the same story.

**Comment by johnnyreilly** [comment] 2017-08-17 06:57
> I had some issues running thread-loader example 

Could you tell me what these were please? It's important to me that our examples are good / working. If there's an issue I'd like to fix it..

**Comment by voodoorider** [comment] 2017-08-17 07:29
Running `npm install && npm start` inside thread-loader example directory gives me:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules should be an array:
   [object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, resource?, resourceQuery?, compiler?, rules?, test?, use? }]

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! thread-loader@1.0.0 start: `webpack --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thread-loader@1.0.0 start script 'webpack --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wowczarczyk/Development/Libraries/ts-loader/examples/thread-loader/npm-debug.log
```

This is on MacBook Pro running macOS Sierra.

**Comment by johnnyreilly** [comment] 2017-08-17 08:01
Thanks - I'll take a look

**Comment by voodoorider** [comment] 2017-08-17 08:04
I think it's just a matter of adding`[]` for `rules`

**Comment by johnnyreilly** [comment] 2017-08-17 08:09
You couldn't give that a quick try could you?

**Comment by voodoorider** [comment] 2017-08-17 08:15
Like so https://github.com/TypeStrong/ts-loader/pull/606 ?

**Comment by johnnyreilly** [comment] 2017-08-17 08:20
That's brilliant! Thanks so much! Will merge later today

**Comment by abirmingham** [comment] 2017-08-30 15:37
FYI for those following this thread - @johnnyreilly [has documented](https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/39) (and solved in a fork?) this issue in fork-ts-checker-webpack-plugin. Thanks John!

I'm still curious to know more about how ts-loader and TypeScript handle syntax errors. Many syntax errors result in semantically-ambiguous code, and I'm surprised that code with syntax errors is able to be compiled at all. Why does the TypeScript API allow this? Does it differentiate between syntax errors which introduce ambiguity and those which do not? Personally I do not think it is desirable for a compiler to guess about the semantics of the following code:
```js
// Note the missing comma below:
const bar = [
    'a',
    'b'
    'c'
];

// Note the semi-colons below:
const biz = {
    a: 1,
    b: 2;
    c: 3;
    d: 4
};

// Note the missing '=>' below:
export const foo = async (bar:number):Promise<void> {
   ...
}
```

**Comment by voodoorider** [comment] 2017-08-30 15:46
Yes, we were also suprised how the compiler is capable of guess some of the syntactical errors:

https://www.typescriptlang.org/play/#src=const%20a%20%3D%20%5B1%202%203%204%205%5D%3B%0D%0Aconst%20fun%20%3D%20()%20%7B%20return%201%3B%7D

but on the other hand it is probably handled by TS compiler's tokenizer which knows what i.e. delimiters should be used in given structures.

**Comment by johnnyreilly** [comment] 2017-08-30 15:50
> FYI for those following this thread - @johnnyreilly has documented (and solved in a fork?) this issue in fork-ts-checker-webpack-plugin. Thanks John!

Hey @abirmingham!  AFAIK the issue is now resolved.  Whilst we're waiting for it to be merged and published to npm you can probably just point any of your `package.json` devDependency for `fork-ts-checker-webpack-plugin` directly to my fork on GitHub here: https://github.com/johnnyreilly/fork-ts-checker-webpack-plugin.  It should (I think) just work. 

You'll also need to add the new `checkSyntacticErrors: true` option when invoking the compiler.  

Once everything's all published I'll update the various ts-loader examples on the site to avoid confusion.

**Comment by abirmingham** [comment] 2017-08-30 16:59
@johnnyreilly thanks! I've seen no issues with the fix so far and we are determining whether to use your fork as a stop-gap measure until it's merged :)

**Comment by johnnyreilly** [comment] 2017-08-31 07:38
@abirmingham merged! https://github.com/Realytics/fork-ts-checker-webpack-plugin/releases/tag/v0.2.8

**Closed by johnnyreilly** 2017-08-31 07:38 UTC

**Comment by abirmingham** [comment] 2017-08-31 16:40
@johnnyreilly thanks!!!
