### ISSUE TITLE
Issue with TypeScript 2.9.1

### ISSUE THREAD

**Issue by manu-st** [TypeStrong/ts-loader#787] opened 2018-06-05 00:27 UTC
### Expected Behaviour
Code should include a require to run properly.

### Actual Behaviour
require is missing in generated code

### Steps to Reproduce the Problem
Not sure.

### Location of a Minimal Repository that Demonstrates the Issue.
I have a file and when I'm compiling using TypeScript 2.9 I get the following:

```
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
const graph_1 = __webpack_require__(50);
class CollectionGraphStore extends graph_1.GraphStore {
    constructor() {
        super(new ProcedureGraphOptions_1.ProcedureGraphOptions());
....
```

As you can see `ProcedureGraphOptions_1` is not included.

If I generate the same code using TypeScript 2.8.3, then I get:

```

var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
const graph_1 = __webpack_require__(51);
const ProcedureGraphOptions_1 = __webpack_require__(122);
class CollectionGraphStore extends graph_1.GraphStore {
    constructor() {
        super(new ProcedureGraphOptions_1.ProcedureGraphOptions());
....
```

Unfortunately I'm at loss at why it is not generating the missing require. If I use `tsc` 2.9.1 from the command line to generate the JavaScript code, the code is properly generated:

```
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
const graph_1 = require("Controls/graph");
const ProcedureGraphOptions_1 = require("Experiment/procedures/ProcedureGraphOptions");
class CollectionGraphStore extends graph_1.GraphStore {
    constructor() {
        super(new ProcedureGraphOptions_1.ProcedureGraphOptions());
...
```

Any idea?

**Comment by johnnyreilly** [comment] 2018-06-05 04:55
None at all I'm afraid; that seems super strange. What does the source code look like that generates this code? There's nothing changed in ts-loader that would seem relevant.

**Comment by johnnyreilly** [comment] 2018-06-05 05:01
It feels like this might be an issue with TypeScript rather than ts-loader - the code is generated by TSC and we just use what it pumps out. Could be worth sticking a `console.log` in the ts-loader codebase at the point where TypeScript emits the code and seeing if it's there at all with 2.9.1: https://github.com/TypeStrong/ts-loader/blob/master/src/index.ts#L71

That would be useful to know. Just hack it into the version in your `node_modules` and see what you find. If it's missing there it's probably a TypeScript issy

**Comment by manu-st** [comment] 2018-06-05 19:43
I'll have a look at it and report back.

**Comment by arackaf** [comment] 2018-06-05 21:27
I'm seeing a similar issue in our code base - an import is being dropped which is leading to a runtime error.

gulp-ts did not have the same problem - I'll run this with tsc and see what happens.

**Comment by arackaf** [comment] 2018-06-05 22:14
Update: the same bug appears with `awesome-typescript-loader`, so there does seem to be something about ts 2.9.1 that's causing webpack loaders to emit incorrect code.

**Comment by arackaf** [comment] 2018-06-05 22:45
I'm working on putting together a workaround, whereby I just tell ts-loader to run an older, working version of typescript (assuming you have the transpileOnly option already set, and are doing type checking in a different process, which I already am).  I *think* the `instance` config option might be for that, but the docs are non-existent for it. 

I tried putting `instance: "folder"` where folder is a directory with a different version of typescript installed in node_modules, but that appears to do nothing.  The closest to docs I could find for it were from this issue: https://github.com/TypeStrong/ts-loader/issues/647 

Hopefully that might help someone else.

**Comment by manu-st** [comment] 2018-06-06 03:35
@arackaf Using an old version of the TypeScript compiler might not be adequate if you want to use the latest language features. We just need to figure out why some require are missing.

**Comment by johnnyreilly** [comment] 2018-06-06 05:11
@arackaf thanks for sharing your code - that's helpful.  Also it's interesting to know that `awesome-typescript-loader` is experiencing the same issue.  This makes me think more than ever

Would one of you be able to give this a try please?

> It feels like this might be an issue with TypeScript rather than ts-loader - the code is generated by TSC and we just use what it pumps out. Could be worth sticking a `console.log` in the ts-loader codebase at the point where TypeScript emits the code and seeing if it's there at all with 2.9.1: https://github.com/TypeStrong/ts-loader/blob/master/src/index.ts#L71

> That would be useful to know. Just hack it into the version in your `node_modules` and see what you find. If it's missing there it's probably a TypeScript issue

Assuming this is a TypeScript API issue it would be good to raise an issue with the TypeScript project to let them know? (I don't know if @DanielRosenwasser will necessarily see the comment here)  There was another issue with 2.9.1 which I reported which has already been fixed (https://github.com/Microsoft/TypeScript/issues/24625); the team are super responsive!

**Comment by johnnyreilly** [comment] 2018-06-06 05:17
> the false positive errors were impossible to figure out

As a complete aside @arackaf  (and I don't want to derail the issue) this made me curious.  Would be interested to know what the false positives were.  I'm still happily using the separate checker.   Obviously your mileage may vary etc but I am interested in issues.

**Comment by arackaf** [comment] 2018-06-06 14:14
@johnnyreilly Ok, I did what you said, and sure enough, the import (it's an ES6 import, not a require()) is indeed gone for the file in question, but **only** with `transpileOnly` set to true. Once I remove that, then the emitted source is correct, and has the import in it again.

I guess this dovetails nicely with the false positives you were asking about. Basically, ts-loader complains about a ton of ts errors, usually involving typings and libs. It ignores some legacy `declare var` statements, and then errors out on things like global `$` or `ko` references, and it complains about things like addEventListener, location, open, etc existing on window, etc.

While I have you, can I trouble you for some help in getting the `instance` property working? Forcing ts-loader to use 2.8.3 while this is worked out is probably my best bet, but I can't for the life of me figure out how to configure it.

Needless to say, if there's anything at all I can do to help get this fixed, please don't hesitate.  /cc @DanielRosenwasser

**Comment by manu-st** [comment] 2018-06-06 15:37
I confirm that I'm also using ts-loader with `transpileOnly` and we use `ForkTsCheckerWebpackPlugin` to perform the type checking as we found this to be faster.

**Comment by manu-st** [comment] 2018-06-06 15:55
I also confirm that dropping `transpileOnly` is causing the code to be generated properly. However this is not a solution for us since it takes 120s with this option disabled and around 45s when it is set to true.

**Comment by arackaf** [comment] 2018-06-06 16:20
The most expeditious band-aid / workaround would be to get that `instance` config property working. If we're only using ts-loader for `transpileOnly` then we could probably pipe it through a side install of ts 2.8 and still get the same output.  (while using our type checker as usual)

Does anyone have any info on how to do that???

**Comment by johnnyreilly** [comment] 2018-06-06 17:14
@arackaf 

> Needless to say, if there's anything at all I can do to help get this fixed, please don't hesitate. 

Thanks for investigating that's awesome. It sounds like there is a bug with the `transpileModule` API in TypeScript 2.9.1.  Please could you raise a ticket against the Typescript project and link back to this issue?

**Comment by arackaf** [comment] 2018-06-06 17:16
Will do!  I don't suppose you have any info on how to use the `instance` option?

**Comment by johnnyreilly** [comment] 2018-06-06 17:54
Thanks! Re: `instance`, does this config help? https://github.com/TypeStrong/ts-loader/blob/master/test/comparison-tests/instance/webpack.config.js

**Comment by johnnyreilly** [comment] 2018-06-06 17:56
Looks like the issue should be fixed in 2.9.2!

https://github.com/Microsoft/TypeScript/issues/24551

**Comment by arackaf** [comment] 2018-06-06 18:03
@johnnyreilly not too much, sadly.  What exactly does "different" mean?  What does it point to?

**Comment by arackaf** [comment] 2018-06-06 18:07
@DanielRosenwasser publish it pleeeeeeease?????

**Comment by johnnyreilly** [comment] 2018-06-06 18:12
>  What exactly does "different" mean? What does it point to?

Nothing. It's an arbitrary label

**Comment by arackaf** [comment] 2018-06-06 18:13
But how do I relate that arbitrary label to a specific install of TypeScript?

**Comment by arackaf** [comment] 2018-06-06 18:27
Oddly enough, this bug is still in ts@next - I checked.  Glad to hear 2.9.2 is shipping at the end of the week.

**Comment by arackaf** [comment] 2018-06-06 18:28
@johnnyreilly also thanks a ton for the info on `instance` - glad to hear I'm not totally crazy :)

**Comment by mhegazy** [comment] 2018-06-06 19:10
`typescript@2.9.2` should be out next week. we have another set of issues to include as well.

but meanwhile can you verify that `typescript@next` addresses the issue?

**Comment by johnnyreilly** [comment] 2018-06-06 20:09
Thanks for that @mhegazy.  According to @arackaf the issue is still in `typescript@next` though:

> Oddly enough, this bug is still in ts@next - I checked

Is the fix definitely in there?

**Comment by mhegazy** [comment] 2018-06-06 20:31
i tried with the sample @arackaf shared and that seemed to work for me on `typescript@next`. He also seemed to suggest that it was fixed on `@next` in https://github.com/Microsoft/TypeScript/issues/24729#issuecomment-395183002. 

on any rate, if you are still running into issues with `typescript@next` can you share a repro?

**Comment by johnnyreilly** [comment] 2018-06-06 20:33
@arackaf could you advise @mhegazy if an issue remains with `typescript@next`?  Sounds like it's all resolved?

**Comment by arackaf** [comment] 2018-06-06 20:34
Nope - I was wrong.  webpack's cache-loader was tricking me :)

It's fixed in ts@next!

**Comment by manu-st** [comment] 2018-06-07 01:15
Just tried with ts@next (i.e. version "3.0.0-dev.20180606") and it doesn't work for me, I'm still getting the same error.

**Comment by arackaf** [comment] 2018-06-07 01:30
@manu-st are you running the cache-loader in your webpack config?  Be sure to delete that if you are.

**Comment by manu-st** [comment] 2018-06-07 04:19
No cache-loader in my config. I've alternated between 2.8.3 and the latest version of TypeScript and going back to 2.8.3 always work.

**Comment by arackaf** [comment] 2018-06-07 04:33
Disconcerting to say the least. I don't suppose this repo is publicly accessible anywhere, that you could point the TS team toward?

**Comment by mhegazy** [comment] 2018-06-07 05:28
Please share a sample where the import is elided. What we care about is how the import is defined and where it is used.

**Comment by manu-st** [comment] 2018-06-07 17:37
In my case, the source code for which I showed the wrong generated code is

```
import { GraphStore } from "Controls/graph";
import { ProcedureGraphOptions } from "Experiment/ProcedureGraphOptions";
export class CollectionGraphStore extends GraphStore
{
   constructor ()
   {
      super (new ProcedureGraphOptions ());
   }
...
}
```

In that file, ProcedureGraphOptions is only used for the call to `super`.

**Comment by johnnyreilly** [comment] 2018-06-07 17:46
@manu-st would you be able to share a simple repo which illustrates this please. It's fairly possible that config may be an issue and without seeing a minimal repo it's hard for the Typescript team to help you. Help them, help you!

**Comment by mhegazy** [comment] 2018-06-07 18:27
The use in super is the original issue, but we believe that was fixed. Can u share more details?

**Comment by arackaf** [comment] 2018-06-07 19:55
@mhegazy - well I'll be ... my problem related to using the import only in super() as well.

@manu-st - I can't help but believe there may be some weird caching issue here.  Can you make certain that's not it by deleting every single output file before doing your rebuild?

**Comment by manu-st** [comment] 2018-06-08 04:38
I managed to reproduce it on a very simple project at https://github.com/manu-st/ts29issue.
Simply use `yarn install` and `yarn start`. It will start an instance of Electron with the dev tools open and you should see the error about Options_1 being undefined.

**Comment by mhegazy** [comment] 2018-06-13 19:54
`typescript@2.9.2` is available now, and should include the fixes for both repros in this thread.

**Closed** 2018-06-26 20:05 UTC
