### ISSUE TITLE
Not compatible with 3.83

### ISSUE THREAD

**Issue by FishOrBear** [TypeStrong/ts-loader#1065] opened 2020-03-11 09:43 UTC
https://github.com/TypeStrong/ts-loader/tree/master/examples/vanilla
package.json
```
{
  "name": "vanilla",
  "main": "index.js",
  "version": "1.0.0",
  "scripts": {
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --progress --color"
  },
  "devDependencies": {
    "ts-loader": "^6.2.1",
    "typescript": "^3.8.3",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  }
}

```

index.js
```
let a = 1 ?? 2;
```

error:
```
ERROR in ./src/index.ts 1:11
Module parse failed: Unexpected token (1:11)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
> let a = 1 ?? 2;
| 
i ｢wdm｣: Failed to compile.
```

**Comment by B3zo0** [comment] 2020-03-11 10:54
Duplicate of #1061 
Set you target something lower than ES2020

**Comment by FishOrBear** [comment] 2020-03-12 04:51
ok

**Closed** 2020-03-12 07:52 UTC
