### ISSUE TITLE
Unable to filter the warning output

### ISSUE THREAD

**Issue by vipcxj** [TypeStrong/ts-loader#922] opened 2019-04-22 02:47 UTC
I use `typings-for-css-modules-loader` to generate the dts file of css and less file. Then the ts will report 
```
WARNING in ./path/to/*.less.d.ts
Module build faild (from ./node_modules/_ts-loader@5.3.3@ts-loader/index.js)
Error: Debug Failure. Output generation failed
    at Object.transpileModule(/path/to/typescrit.js:108135:29)
    ...
```
Even if I config the `reportFiles` to `['src/**/*.(ts,tsx)']`, it not work.
And `['src/**/*.(ts,tsx)', '!src/**/*.{css,less,sass,scss}.d.ts']` still not work.

**Comment by vipcxj** [comment] 2019-06-23 09:56
any news？

**Comment by Yidada** [comment] 2019-11-04 06:53
why close this ? Met the same issues.

**Comment by johnnyreilly** [comment] 2019-11-04 08:01
Reopening so @Yidada can work on this.

**Comment by vipcxj** [comment] 2020-01-06 01:30
any news?

**Comment by purple-force** [comment] 2020-02-19 06:39
any news? The same to me.

**Comment by purple-force** [comment] 2020-02-20 10:05
@vipcxj @Yidada  After seeing https://stackoverflow.com/questions/38231645/typescriptwebpack-typescript-emmited-no-output-for-index-d-ts，I guess the error is caused by lack of appropriate loader    to handle `.d.ts` files, so i use  ignore-loader to ignore `{css,less,sass,scss}.d.ts` files and it works for me.
I guess when setting extensions by webpack, `*.css.d.ts` is also handled by `ts-loader` due to `test: \\.ts\`, which hitting this rule, but can not handle it.

**Closed** 2020-05-03 09:56 UTC
Labels: wontfix
