### ISSUE TITLE
Error when using typescript 2.1

### ISSUE THREAD

**Issue by sarod** [TypeStrong/ts-loader#416] opened 2016-12-14 21:44 UTC
First of all thanks for the great work.

I get the following error when using ts-loader with typescript 2.1.4. It works fine with typescript 2.0.10

```
TypeError: Cannot read property 'getOptionsDiagnostics' of undefined
    at Object.getCompilerOptionsDiagnostics (/home/me/git/project/node_modules/typescript/lib/typescript.js:79004:27)
    at provideCompilerOptionDiagnosticErrorsToWebpack (/home/me/git/project/node_modules/ts-loader/dist/after-compile.js:33:92)
    at Compiler.<anonymous> (/home/me/git/project/node_modules/ts-loader/dist/after-compile.js:14:9)
    at next (/home/me/git/project/node_modules/tapable/lib/Tapable.js:83:14)
    at Compiler.<anonymous> (/home/me/git/project/node_modules/webpack/lib/CachePlugin.js:61:4)
    at Compiler.applyPluginsAsync (/home/me/git/project/node_modules/tapable/lib/Tapable.js:85:13)
    at /home/me/git/project/node_modules/webpack/lib/Compiler.js:476:10
    at Compilation.applyPluginsAsync (/home/me/git/project/node_modules/tapable/lib/Tapable.js:73:70)
    at /home/me/git/project/node_modules/webpack/lib/Compilation.js:627:18
    at Compilation.applyPluginsAsync (/home/me/git/project/node_modules/tapable/lib/Tapable.js:73:70)
    at /home/me/git/project/node_modules/webpack/lib/Compilation.js:618:10
    at Compilation.applyPluginsAsync (/home/me/git/project/node_modules/tapable/lib/Tapable.js:73:70)
    at /home/me/git/project/node_modules/webpack/lib/Compilation.js:613:9
    at Compilation.applyPluginsAsync (/home/me/git/project/node_modules/tapable/lib/Tapable.js:73:70)
    at /home/me/git/project/node_modules/webpack/lib/Compilation.js:609:8
    at Compilation.applyPluginsAsync (/home/me/git/project/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.seal (/home/me/git/project/node_modules/webpack/lib/Compilation.js:555:7)
    at /home/me/git/project/node_modules/webpack/lib/Compiler.js:473:16
    at /home/me/git/project/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (/home/me/git/project/node_modules/webpack/lib/Compilation.js:452:10)
    at /home/me/git/project/node_modules/webpack/lib/Compilation.js:423:12
    at /home/me/git/project/node_modules/webpack/lib/Compilation.js:335:10
```

I'm currently trying to reproduce on a small project.

**Comment by sarod** [comment] 2016-12-14 21:58
You can find a small project reproducing the issue here: https://github.com/sarod/ts-loader-issue416/tree/master.

**Comment by johnnyreilly** [comment] 2016-12-15 06:41
That's strange - we've no changes so I'm inclined to think this isn't related to ts-loader. It may be a change in behaviour of tsc itself.

**Comment by johnnyreilly** [comment] 2016-12-15 06:59
I've just experienced this when running our test pack locally.  Our `tsconfigInvalidFile` test is failing.  However it didn't break last night: https://travis-ci.org/TypeStrong/ts-loader/jobs/184064429

Something out there on the web is **broken**

**Comment by johnnyreilly** [comment] 2016-12-15 07:17
Yup - just queued a build: https://travis-ci.org/TypeStrong/ts-loader/builds/184161815

It's not TypeScript 2.1 related; the same affects 2.0 as well.  We haven't changed - something else has.  If you could find out what that would be awesome!

**Comment by johnnyreilly** [comment] 2016-12-15 09:27
okay - just compared the npm installs for each build (makes me really wish I'd switched to Yarn) and here are the differences:

- debug@2.4.4 (broken) debug@2.4.2 (working)
- typings-core@2.2.0 (broken) typings-core@2.1.0 (working)
- popsicle@9.0.0 (broken) popsicle@8.20 (working)

**Comment by johnnyreilly** [comment] 2016-12-15 11:18
Non of those ought to be the cause though....

**Comment by johnnyreilly** [comment] 2016-12-15 11:34
Actually ignore all of this - it appears to be unrelated

**Comment by mutsys** [comment] 2016-12-16 02:14
I am experiencing this issue as well. Is there anything I can do to help get this resolved?

**Comment by johnnyreilly** [comment] 2016-12-16 05:56
Thanks for offering! 

For now I don't think it's a ts-loader issue - particularly given your findings.

I'd suggest raising an issue with the TypeScript team as I'm guessing there was some kindof compiler change.

**Comment by DomiR** [comment] 2016-12-19 13:44
Quickfix, as typescript can't import other filetypes at the moment: 
```diff
-import 'normalize.css';
+declare var require;
+require('normalize.css');
```

**Comment by QuantumInformation** [comment] 2016-12-19 22:35
@DomiR is this issue/fix relevant to this:
http://stackoverflow.com/questions/41178496/upgrading-to-typescript-2-1-results-in-cant-resolve-file-errors-in-previous

**Comment by HerringtonDarkholme** [comment] 2016-12-27 09:48
Fix has been merged in master branch. Let's wait patiently.
https://github.com/Microsoft/TypeScript/pull/13136

**Comment by mutsys** [comment] 2016-12-29 04:11
I just did a quick check of `ts-loader@1.3.3` with the most recent 2.1/2.2 builds of `typescript`:
```
typescript@2.1.5-insiders.20161220
typescript@2.2.0-dev.20161228
```

In both cases everything works as expected. It appears that the typescript team has resolved the issue. I would recommend that you just add a note to the README and close this issue now.

**Closed** 2016-12-31 13:17 UTC
