### ISSUE TITLE
Webpack 2.0 - Cannot read property 'unsafeCache' of undefined

### ISSUE THREAD

**Issue by donaldpipowitch** [TypeStrong/ts-loader#283] opened 2016-09-20 07:22 UTC
## Please read right to the bottom of this thread for an approach that seems to work.

Using `webpack@2.1.0-beta.23`:

```
ERROR in ./src/index.tsx
Module build failed: TypeError: Cannot read property 'unsafeCache' of undefined
    at makeResolver (/Users/foo/node_modules/ts-loader/resolver.js:35:57)
    at ensureTypeScriptInstance (/Users/foo/node_modules/ts-loader/index.js:207:20)
    at Object.loader (/Users/foo/node_modules/ts-loader/index.js:387:14)
```

Used as:

```
export const tsLoader = {
  test: /\.ts(x?)$/,
  loader: `ts-loader?silent=true`
};

```

**Comment by josiah1888** [comment] 2016-09-20 19:38
+1 heeeelp

**Comment by donaldpipowitch** [comment] 2016-09-20 19:43
I switched to https://github.com/s-panferov/awesome-typescript-loader. Works fine.

**Comment by johnnyreilly** [comment] 2016-09-20 20:58
I'm afraid ts-loader is untested with WebPack 2 to my knowledge. awesome-typescript-loader is probably the best choice if you're after WebPack 2.0 support now. Myself I haven't used 2.0 as it's still in beta (and 1 handles my use cases)

**Comment by r-park** [comment] 2016-09-21 16:38
For me, this only happens when I use the `LoaderOptionsPlugin` with an `options` key:
```js
new LoaderOptionsPlugin({
  debug: false,
  options: { ... }
})
```

**Comment by jeffijoe** [comment] 2016-09-25 10:45
I tried `awesome-typescript-loader` and couldn't get it working so I decided to take a stab at figuring out how to fix this.

@r-park @johnnyreilly @donaldpipowitch @josiah1888  by `console.log`ing in the place the error occured, I found that the `options` is actually the `options` from the `LoaderOptionsPlugin`. By doing this:

```js
new LoaderOptionsPlugin({
  debug: false,
  options: {
    resolve: {}
  }
})
```

Everything runs again.

**Comment by johnnyreilly** [comment] 2016-10-09 04:24
Thanks @jeffijoe  - we should probably include this in the docs somewhere to improve discovery.  Well done for finding out!

**Comment by nitimmerman** [comment] 2016-11-10 14:17
@jeffijoe: Thanks! That did the trick for me also!

**Comment by schickling** [comment] 2016-11-15 15:14
Also switched to `awesome-typescript-loader`. Any update when this will work again out-of-the-box without the workaround (which broke SASS for me).

**Comment by clydin** [comment] 2016-11-15 15:32
The workaround isn't really a workaround as the resolver is not properly configured if you pass in an empty resolve object.

The issue is that when `LoaderOptionsPlugin` is used, the loader doesn't get the full webpack config but instead only what is contained within the object provided to `LoaderOptionsPlugin`.

**Comment by donaldpipowitch** [comment] 2016-12-09 10:59
@jeffijoe Your workaround seems to work for me now without visible problems. But it would be great if the workaround wouldn't be needed.

**Comment by jeffijoe** [comment] 2016-12-09 11:01
@donaldpipowitch Me too, this is how I feel about it:

![In the ghettoooo](https://media.giphy.com/media/krEB8CfiwkGuQ/giphy.gif)

**Comment by johnnyreilly** [comment] 2016-12-09 12:28
Would someone like to submit a PR to resolve this?

**Comment by johnnyreilly** [comment] 2016-12-09 22:21
Related docs: https://webpack.js.org/guides/migrating/#loaderoptionsplugin-context

**Comment by johnnyreilly** [comment] 2016-12-10 06:20
I've documented the workaround in the readme here: https://github.com/TypeStrong/ts-loader#webpack

**Comment by johnnyreilly** [comment] 2016-12-20 05:28
We now have an example in our examples section which demonstrates using ts-loader with webpack 2. I'm still not sure if the unsafe cache thing is actually a ts-loader issue; it feels like required configuration. FWIW in our example we supply all the webpack config options to the loader options plugin.

**Comment by johnnyreilly** [comment] 2017-02-06 07:57
The workaround is now documented on the readme and since this is for the Loader Options Plugin which is due to be short-lived I'm going to close this

**Closed by johnnyreilly** 2017-02-06 07:57 UTC
Labels: help wanted
