### ISSUE TITLE
HMR not working consistently

### ISSUE THREAD

**Issue by subvertallchris** [TypeStrong/ts-loader#351] opened 2016-10-31 16:47 UTC
Sorry for the vague title but I'm having trouble capturing it concisely. Basically, I'm finding that the loader does not hot reload content when I expect it to, though if I move back to `awesome-ts-loader`, it does. For example, changing some text in a `tsx` file will result in a complete reload with `ts-loader`, but `awesome-ts-loader` correctly hot reloads. I'd like to use this library instead of the other, since they seem to have stopped updating regularly, but all the reloads are pretty disruptive.

I'm using TS 2.0.6 and ts-loader 0.9.5, though I found this problem in prior recent versions, as well. I'm not sure where to start troubleshooting this, so please excuse me if this issue is erroneous. Happy to provide any additional information. Thanks!

**Comment by johnnyreilly** [comment] 2016-10-31 17:56
Hi @subvertallchris,

Are you sure that it was 0.9.5 that was problematic?  We had a regression which was fixed with 0.9.4:

https://github.com/TypeStrong/ts-loader/pull/322

**Comment by johnnyreilly** [comment] 2016-10-31 18:03
Fwiw I'm pretty sure awesome TypeScript loader is still actively supported. It's only been a month or so since the last release

**Comment by subvertallchris** [comment] 2016-10-31 18:10
Yup, I just checked again and confirmed that I am using 0.9.5. I'm not sure how to go about troubleshooting this, any recommendations?

**Comment by johnnyreilly** [comment] 2016-10-31 18:13
I would take a look at the code where we introduced and then fixed the regression. It could be worth asking @dopare

**Comment by HerringtonDarkholme** [comment] 2016-11-08 01:29
Hi, can you add an minimal reproduction for hot reload issue? I have found many issues say atl supports HMR not tsl and many other issues say tsl supports HMT but not atl.

**Comment by subvertallchris** [comment] 2016-11-14 17:02
Will do when I have the opportunity, sorry for the delay.

**Comment by ReDrUm** [comment] 2017-03-09 23:41
FWIW It's been working fine for my team under 1.3.3 but upgrading to 2.0.1 now throws compilation typing errors when attempting to rebuild under an HRM scenario. I don't have any code i can share to reproduce it here's an example of a type error which certainly doesn't occur on initial builds:
```
error TS2322: Type 'Promise<CustomType>' is not assignable to type 'Promise<T>'.
  Type 'CustomType' is not assignable to type 'T'.
```

**Comment by johnnyreilly** [comment] 2017-03-10 06:05
It's possible that this is webpack 2 rather than ts-loader related. Very little changed in the move from 1.x to 2.x in ts-loader. Mostly it was just removing support for old node

**Closed** 2017-10-20 09:17 UTC
Labels: needs more info
