### ISSUE TITLE
Webpack watch missing changed files

### ISSUE THREAD

**Issue by KnisterPeter** [TypeStrong/ts-loader#697] opened 2017-12-19 13:58 UTC
### Expected Behaviour
Detect all changed files used in a compilation
### Actual Behaviour
Some files are missing in some cases
### Steps to Reproduce the Problem
https://github.com/KnisterPeter/webpack-multi-app-test

Run `npm run watch` and change `src/core/plugin.ts`.
It is expected that `src/sub/index.tsx` fails afterswards.

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/KnisterPeter/webpack-multi-app-test

The problem is within the `watch-run`. Changed files are filtered here. Maybe its deeper and webpack does not set correct timestamps.

https://github.com/TypeStrong/ts-loader/blob/master/src/watch-run.ts#L25

**Comment by johnnyreilly** [comment] 2017-12-19 14:48
Thanks for the minimal repro repo - that's always appreciated.  I suspect the issue is that the file in question is interfaces only; i.e. it produces no JS output which means file changes result in no changes to the JS output.  As far as webpack is concerned, there wasn't any output before; there isn't now either.

There's not an immediately obvious solution to this.  However, I'm hopeful that when the new watch API changes get merged (https://github.com/TypeStrong/ts-loader/pull/685) this may resolve the issue.

**Comment by KnisterPeter** [comment] 2017-12-19 14:54
Right now there is at least the defintion file updated. Wouldn't it this idea be possible:

1. Filter the list of files as it is done now but exclude `.d.ts` files.
1. Always handle `.d.ts` files as if they where touched.

**Comment by KnisterPeter** [comment] 2017-12-19 15:20
To give some more info here, this is the content of the times object in `watch-run.ts`:

```js
{
  '/x/webpack-test/src/sub/app.tsx': 1513681246518,
  '/x/webpack-test/src/sub/index.tsx': 1513691257828,
  '/x/webpack-test/src/sub/package.json': 1513679868805,
  '/x/webpack-test/src/sub/tsconfig.json': 1513679868805,
  '/x/webpack-test/dist/core/index.d.ts': 1,
  '/x/webpack-test/dist/core/plugin.d.ts': 1,
  '/x/webpack-test/node_modules/@types/node/index.d.ts': 1,
  '/x/webpack-test/node_modules/@types/node/inspector.d.ts': 1,
  '/x/webpack-test/node_modules/@types/react-dom/index.d.ts': 1,
  '/x/webpack-test/node_modules/@types/react/global.d.ts': 1,
  '/x/webpack-test/node_modules/@types/react/index.d.ts': 1,
  '/x/webpack-test/node_modules/typescript/lib/lib.d.ts': 1
}
```
Everything with a timestamp of 1 and not 'living' in `node_modules` could be seen as updated. These files are all part of the current compilation and therefore part of the ts Program.

**Comment by johnnyreilly** [comment] 2017-12-19 15:54
I'm open to PRs that fix the issue - I'd be happy to advise along the way

**Closed** 2018-01-30 19:02 UTC

**Comment by ZSkycat** [comment] 2018-10-25 11:43
I have encountered the same problem. The reason for this problem is not just a  pure types file, but a ts file that is not actually used. That is, only `type` or `interface` is imported.

This problem can be solved by `import './type';`

Don't worry. The webpack production mode can removes empty modules and tree shaking. This won't have extra code being packaged. 😄 

## my case

type.ts
```ts
export interface InterfaceA {
    a1: number;
    a2: string;
}

export function test() {
    console.log('test');
}
```

index.ts
```ts
import { InterfaceA } from './type';
// import './type';

export function app(value: InterfaceA) {
    console.log(value.a1.toFixed(0));
    console.log(value.a2.trim());
}
```
